### ISSUE TITLE
Latest release does not fix 'new project' popup

### ISSUE THREAD

**Issue by chrisradford** [tareq1988/wp-project-manager#52] opened 2015-01-26 13:49 UTC
The latest release (0.4.5) claims to fix the 'new project' popup in the backend, however it appears to still be broken. Theme in use is Twenty Fourteen and no other plugins are active on the site.

![screen shot 2015-01-26 at 13 46 42](https://cloud.githubusercontent.com/assets/743548/5900536/2298fb10-a562-11e4-91fe-5c17cb3e7ae5.png)

**Comment by chrisradford** [comment] 2015-01-26 17:40
To clarify this, WordPress 4.1 still shows the above issue but it's not showing on older versions (4.0 I believe is OK)

**Comment by chrisradford** [comment] 2015-01-26 18:09
Working on a pull request for this; the removal of `package.json` makes it difficult to get Grunt setup — are you using a different tool now instead of Grunt or am I missing something? Thanks!

**Comment by tareq1988** [comment] 2015-01-26 19:03
I am adding the `package.json` again. The issue is being fixed in the next commit. Don't need a pull request for now :)

**Closed** 2015-01-26 19:04 UTC

**Comment by chrisradford** [comment] 2015-01-26 22:04
:+1: Thanks, will check this out in the AM!

**Comment by chrisradford** [comment] 2015-01-27 11:53
This works correctly on the backend, however in the Frontend Plugin the 'x' appears to still be missing.

![screen shot 2015-01-27 at 11 48 47](https://cloud.githubusercontent.com/assets/743548/5917945/8db7d674-a61a-11e4-8bfc-6980c5cface1.png)

It appears that the plugin generates the following in WP-Admin:

```html
<button type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-dialog-titlebar-close" role="button" title="Close">
  <span class="ui-button-icon-primary ui-icon ui-icon-closethick"></span>
  <span class="ui-button-text">Close</span>
</button>
```

Whilst the Frontend Plugin produces:

```html
<button type="button" class="ui-dialog-titlebar-close"></button>
```

I'm aware this is probably the wrong Github repo to report this issue on but since the other is presumably private, I'm hoping this is useful.
